export const path = {
  auth: "/auth",
  login: "/auth/login",
  signup: "/auth/signup",
  forgotPassword: "/auth/forgot-password",
  verification: "/auth/verification",
  error: "*",
  notFound: "404",
  home: "/",
  exchange: "/exchange",
  prices: "/prices",
  wallet: "/wallet",
  nft: "/nft",
  transaction: "/transaction",
  blog: "/blog",
};
